### ISSUE TITLE
Allow Reordering

### ISSUE THREAD

**Issue by cwmke** [julio641742/extend-panel-menu#1]
Any chance of adding a config menu with an option to reorder the new panel menus? For example, I like my clock at the center of the panel and would put sound, internet and battery on the far right. Thanks for the great extension!

**Comment by julio641742** [comment]
I'll look into it, but no promises

**Comment by julio641742** [comment]
It's up now, you can try the feature now.

**Comment by cwmke** [comment]
Works great. Thanks!
