### ISSUE TITLE
Brightness/Power indicator problem at start

### ISSUE THREAD

**Issue by matteotanca** [julio641742/extend-panel-menu#12]
I reinstalled it today to see if translation was in. It's not. I'll wait :)

However I think there is an old bug that you solved in 5.0 : 

- when gnome shell starts the brightness icon is displayed in place of the battery in my laptop, and it have not power options. If I open the extension settings to disable and re-enable again the brightness indicator, I can see my battery and power options too.

**Comment by julio641742** [comment]
I think it works now. The version on gnome shell extensions website is bit behind, so I would recommend clonning this repo and manually installing it

**Comment by matteotanca** [comment]
Yeah it works very well. Also i like the user icon instead of username. Seem very solid now thanks
