### ISSUE TITLE
Switch notifications icon if there's some notifications

### ISSUE THREAD

**Issue by bil-elmoussaoui** [julio641742/extend-panel-menu#14]
I don't know if it's possible to know if there's any notification not read yet, if so it would be great to switch the icons 
You can use those icons 
https://github.com/numixproject/numix-icon-theme/blob/master/Numix/scalable/status/notifications-symbolic.svg
https://github.com/numixproject/numix-icon-theme/blob/master/Numix/scalable/status/notification-new-symbolic.svg
as a fallback if the theme doesn't have them (which is the case on Adwaita)

**Comment by julio641742** [comment]
Thanks, I'll look into it but no promises

**Comment by julio641742** [comment]
It is now available in the latest commit
