### ISSUE TITLE
Moves calendar icon from centre

### ISSUE THREAD

**Issue by Deus-Rex** [julio641742/extend-panel-menu#16]
I prefer to have the calendar at the centre of the top bar, but this extension moves it to the right. Any way to avoid this?

**Comment by julio641742** [comment]
Right now there is no way of doing that, but I do plan to bring that feature as an option in a future release

**Comment by julio641742** [comment]
The latest commit implements moving indicatos to the center, if that is what you are looking for

**Comment by Deus-Rex** [comment]
Nice work. I'll wait for it to be included in the Gnome Extensions site for the convenience before trying out out again. I appreciate you taking the time to implement this for those of us wanting it. I guess this can be marked as closed now, cheers!
