### ISSUE TITLE
Multiple dates displaying

### ISSUE THREAD

**Issue by duryjames** [julio641742/extend-panel-menu#17]
When using with [Dash to panel](https://extensions.gnome.org/extension/1160/dash-to-panel/), I get multiple dates displaying, I've attached a screenshot to help:

![extend-panel-menu](https://cloud.githubusercontent.com/assets/668579/26284477/5bea0fae-3e34-11e7-9364-b3eeb944ad7a.png)

**Comment by julio641742** [comment]
I fixed the problem in the latest commit, it works fine now

**Comment by bil-elmoussaoui** [comment]
This still happens if gnome shell crashes, and restarted.
