### ISSUE TITLE
Volume icon

### ISSUE THREAD

**Issue by redpop1** [julio641742/extend-panel-menu#18]
Volume icon dissapear after wake up from sleep.
Ubuntu gnome 16.04

**Comment by mentofa123** [comment]
Also, the Wireless Network i am connected to, doesn't appear until i reloaded the Gnome shell. 
Manjaro Gnome 17.0.1 Gnome 3.24

**Comment by julio641742** [comment]
The latest commit fixes this problem, if the problem persists, please let me know

**Comment by mentofa123** [comment]
Fix question, may you can push this to the gnome extension site?
