### ISSUE TITLE
Extension is loaded in english language

### ISSUE THREAD

**Issue by matteotanca** [julio641742/extend-panel-menu#19]
Hi Julio,

reinstalled your extension this morning and I don't know how to set it to use Italian language.

**Comment by julio641742** [comment]
That is weird, I haven't changed any translation file. Did you installed it via this repo or gnome extensions website?

**Comment by matteotanca** [comment]
Both installs tried, only english language here.

**Comment by matteotanca** [comment]
![schermata del 2017-05-24 11-29-23](https://cloud.githubusercontent.com/assets/5741224/26396767/74b32bc8-4074-11e7-805c-cc7edcfe050c.png)

here's a screenshot, as you can see is in english

**Comment by julio641742** [comment]
Do you still have the problem?

**Comment by matteotanca** [comment]
Problem solved, thank you man!!
