### ISSUE TITLE
Volume icon appears only after regulating volume

### ISSUE THREAD

**Issue by matteotanca** [julio641742/extend-panel-menu#20]
When extension start volume icon is not visible, appears only if i adjust volume.

**Comment by Arch-Lover** [comment]
same thing for me(Arch Linux Gnome 3.24.2)

**Comment by julio641742** [comment]
Are you both using the latest commit?
I don't have that problem on my side, but please try installing it again via the github repo

**Comment by matteotanca** [comment]
You right, the github repo works fine, volume icon is here
