### ISSUE TITLE
Cannot see Sound Output Device Chooser options

### ISSUE THREAD

**Issue by matteotanca** [julio641742/extend-panel-menu#21]
Maybe there's still problems with the compatibility with Sound Output Device Chooser becouse I can see it working only if i disable your extension.

**Comment by bil-elmoussaoui** [comment]
It's already possible if you try the master version

**Comment by julio641742** [comment]
Like @bil-elmoussaoui said, it is working just fine. Please try installing the extension again

**Comment by matteotanca** [comment]
You right, installed from github repo and now its working. THANKS
