### ISSUE TITLE
problem with wordclock

### ISSUE THREAD

**Issue by Arch-Lover** [julio641742/extend-panel-menu#23]
hi & thnx for great extension!
some how i cant have both your extension and word clock active at the same time!
any idea?
![image](https://cloud.githubusercontent.com/assets/14254646/26319463/5ece6854-3f34-11e7-8e06-60ad2568ad2e.png)

**Comment by julio641742** [comment]
Thanks for the feedback, I am currently working on it

**Comment by julio641742** [comment]
Fixed in latest commit, enjoy
