### ISSUE TITLE
Icon for volume control sometimes disappears

### ISSUE THREAD

**Issue by michael-reichert** [julio641742/extend-panel-menu#25]
The icon for volume control sometimes disappears from the panel:
![screenshot1](https://cloud.githubusercontent.com/assets/28943020/26436201/2103fb00-4115-11e7-910c-1cf7b45da256.png)
Once I press Fn-F10/11/12 for volume control, the icon appears again:
![screenshot2](https://cloud.githubusercontent.com/assets/28943020/26436200/21039872-4115-11e7-8958-d54ebcaf2d68.png)
So everything works in principle.

I am using Ubuntu Gnome 17.04.

**Comment by MKN-dev-LINUX** [comment]
Volume Icon disappears. Generally disappears when I am adjusting other extensions such as Gno-menu. 

In addition, "indicators" layout does not save. I have to reposition my icons every restart/logout.

Ubuntu Gnome 17.04

**Comment by AlexGluck** [comment]
After lock\sleep volume Icon disappears.

**Comment by ser** [comment]
I can confirm, volume icon is not visible at all. Topicons plus installed as well.

**Comment by kkomara** [comment]
I have same issue on Ubuntu Gnome 16.04.02.  Is there any fix or work around for this yet ?

**Comment by AlexGluck** [comment]
@kkomara No, now try reload gnome shell.

**Comment by AlexGluck** [comment]
Latest master, have fixed this issue.

**Comment by kkomara** [comment]
Is the issue with the volume icon disappearing supposed to be fixed ?  From  comment above "Latest master, have fixed this issue" I thought it was fixed.  I removed extend-panel-menu and re-installed it.  Problem still there.  Rebooted my Ubuntu PC - volume control was there after initial login after reboot.  Locked my Linux PC.  Logged into Linux PC - Volume control missing.  Tried changing its position order - problem still there.  I think I am running the latest version of extend-panel-menu - but how can I tell ?

**Comment by AlexGluck** [comment]
@kkomara On fedora 26@xorg, gnome 3.24 latest master fixed this problem. What is your version OS and Gnome?

**Comment by kkomara** [comment]
Wow - thanks for the quick response !!  I am using stock Ubuntu 16.04.02 Gnome.  I can get more details if you need them.

**Comment by kkomara** [comment]
really hate to go through a GNOME update - and possible compromise my system. Is there any other way to figure out what actually fixed the issue ?

**Comment by kkomara** [comment]
why just the volume icon disappearing ??

**Comment by AlexGluck** [comment]
@kkomara may be yes, idk. i'm simple user, not developer or owner.

**Comment by kkomara** [comment]
I too AlexGluck's suggesting and upgraded my GNOME to 3.20 which is the latest available for Ubuntu 16.04.02.  This fixed my issues with the Volume Icon disappearing.  Upgrade went great - and this fixed a few other issues that I was having.  Thanks AlexGluck for the help !!!

**Comment by AlexGluck** [comment]
@julio641742 this bug not implemented already. Close?
