### ISSUE TITLE
View list of networks to connect to when clicking on the network indicator

### ISSUE THREAD

**Issue by PizzicatoWolf** [julio641742/extend-panel-menu#26]
When you click on the icon, you can open a drop down menu for location settings, but network settings takes you to an application rather than acting as a drop down menu as well. Would be more convenient if this was designed like that. 

Edit: a feature would be nice to see a drop down list of available wifi hotspots to connect to.

**Comment by AlexGluck** [comment]
![2017-06-29 13-37-02](https://user-images.githubusercontent.com/8583390/27684126-47d8a80c-5cd1-11e7-8ad8-53b8d5e712d8.png)
After lock\sleep current wifi connection disappears.

![2017-06-29 13-40-37](https://user-images.githubusercontent.com/8583390/27684125-47d87990-5cd1-11e7-9682-df1dc8e865bb.png)

List extension
```
AlternateTab			
Arc Menu			
Caffeine			
CPU Power Manager			
Dash to Panel			
Disable Barrier Support			
Disconnect Wifi			
Extend Panel Menu			
Extension Update Notifier			
Imgur Screenshot Uploader			
Jenkins CI Server Indicator			
KStatusNotifierItem/AppIndicator Support			
No Topleft Hot Corner			
Panel OSD			
Refresh Wifi Connections			
Remmina Search Provider			
Removable Drive Menu			
Remove Dropdown Arrows			
Status Area Horizontal Spacing			
TopIcons Plus			
Transcode App Search			
Trash			
User Themes
```
Fedora 25.

**Comment by julio641742** [comment]
Thanks for the feedback @PizzicatoWolf  It is a feature I want to bring in the future

Sorry @AlexGluck I am still trying to fix that

**Comment by AlexGluck** [comment]
This happen because extension load later or faster. Try add temporary hook, refresh or reload extension.

**Comment by julio641742** [comment]
Great idea @AlexGluck I didn't think of that before

**Comment by julio641742** [comment]
Your idea of a network list is not implemented in the latest commit @PizzicatoWolf

**Comment by PizzicatoWolf** [comment]
:(

**Comment by AlexGluck** [comment]
Works good, thx for latest version. @PizzicatoWolf try update extension from github, all good.
