### ISSUE TITLE
Icons and calendar disappear when resuming

### ISSUE THREAD

**Issue by Hombremaledicto** [julio641742/extend-panel-menu#27]
Hi, I'm using this extension(latest commit) with Gnome 3.24, tried with both a vanilla Gnome Shell and with dash to panel. After resuming the laptop (or unlocking the session) all of the icons - volume, network, etc... -  and calendar disappear. I have to restart Gnome Shell to make them appear everytime.

**Comment by julio641742** [comment]
The latest commit may solve that problem, please check try it out

**Comment by Hombremaledicto** [comment]
Sorry for the lag, somehow i've missed the notification for your reply(and to check for new commits)
After updating today to the latest is working fine(on a side note, you might want to look for the geolocalization indicator maybe).
