### ISSUE TITLE
Indicator new notification not disappear.

### ISSUE THREAD

**Issue by AlexGluck** [julio641742/extend-panel-menu#30]
![2017-06-29 13-53-58](https://user-images.githubusercontent.com/8583390/27684452-bf96d99e-5cd2-11e7-9f63-56c88a15cd6a.png)

This happen because not all notification show. If call hotkey "Super+V" we see some notification

![2017-06-29 14-13-03](https://user-images.githubusercontent.com/8583390/27685090-5ce128c4-5cd5-11e7-848b-45ed626b2b09.png)

List extension
```
AlternateTab			
Arc Menu			
Caffeine			
CPU Power Manager			
Dash to Panel			
Disable Barrier Support			
Disconnect Wifi			
Extend Panel Menu			
Extension Update Notifier			
Imgur Screenshot Uploader			
Jenkins CI Server Indicator			
KStatusNotifierItem/AppIndicator Support			
No Topleft Hot Corner			
Panel OSD			
Refresh Wifi Connections			
Remmina Search Provider			
Removable Drive Menu			
Remove Dropdown Arrows			
Status Area Horizontal Spacing			
TopIcons Plus			
Transcode App Search			
Trash			
User Themes
```
Fedora 25.

**Comment by julio641742** [comment]
Fixed, thanks for the feedback
