### ISSUE TITLE
Please add button "Show Desktop".

### ISSUE THREAD

**Issue by AlexGluck** [julio641742/extend-panel-menu#31]
How in extension "Dash to Panel" or fix place button after sleep\lock.

![2017-06-29 14-19-30](https://user-images.githubusercontent.com/8583390/27685274-22ccd736-5cd6-11e7-8e3a-2baffe12e437.png)

**Comment by yurividal** [comment]
same issue here. it keeps changing the position arter screen sleep

**Comment by julio641742** [comment]
I fixed this issue in the latest commit, enjoy 👍
