### ISSUE TITLE
Version # and Update Available

### ISSUE THREAD

**Issue by heynnema** [julio641742/extend-panel-menu#33]
I had problem with the extend-panel-menu. It crashed GNOME Shell, It made the speaker icon disappear. And notifications didn't show up under that icon. So I downloaded the github code and installed it. It seems to have solved most of the above problems (still testing). But GNOME now keeps telling me that an update is available. I can't find a version # anywhere. So how does it know that there's an update available? How can I stop the notification, as I have the latest version, I think.

**Comment by julio641742** [comment]
It is because i didn't write the version in the metadata.json file, so GNOME thinks that you are using an old version. This problem is fixed as of now 👍
