### ISSUE TITLE
Incompatible with Dash-to-Panel (show desktop button)

### ISSUE THREAD

**Issue by yurividal** [julio641742/extend-panel-menu#34]
When using this extention with Dash-to-panel, if i set dash to panel to show the "show desktop button", the button shows fine first, but then, after the screen turns off and back on, the show desktop button is moved to the left of extend-panel-menu ... check the screenshots: 
![screenshot from 2017-07-06 09-36-00](https://user-images.githubusercontent.com/8555749/27992028-93609354-6481-11e7-90ea-e88273b92369.png)
![screenshot from 2017-07-06 10-17-34](https://user-images.githubusercontent.com/8555749/27992029-960247ba-6481-11e7-9646-348a9a9c24ef.png)

**Comment by julio641742** [comment]
I fixed this issue in the latest commit 👍
