### ISSUE TITLE
Icon not show when appears notifications.

### ISSUE THREAD

**Issue by AlexGluck** [julio641742/extend-panel-menu#36]
All indicators shift, but icon not visibility.
![2017-07-14 18-56-52](https://user-images.githubusercontent.com/8583390/28219916-5a059b1a-68c6-11e7-9636-c8f5863b5e35.png)

**Comment by julio641742** [comment]
Please try using the latest version, and report back

**Comment by AlexGluck** [comment]
![2017-07-15 16-09-54](https://user-images.githubusercontent.com/8583390/28239584-27869ff6-6978-11e7-8cb7-5ebbf1c3b045.png)
Latest master from github, not working. And change format of date in the calendar indicator not visible in settings.

**Comment by AccountOneOff** [comment]
The extension.js file has the notification icon set to false.

        this._newMessageIndicator.actor = new St.Icon({
            icon_name: "notification-new-symbolic",
            style_class: "system-status-icon",
            visible: false

**Comment by julio641742** [comment]
I can't reproduce the problem, the extension works just fine on every single computer I have

**Comment by AlexGluck** [comment]
I update OS to Fedora 26, may this info help you. Gnome 3.24 and listing extensions below:
```
AlternateTab
Arc Menu
Caffeine
Dash to Panel
Disable Barrier Support
Disconnect Wifi
Extend Panel Menu
Extended Gestures
Extension Update Notifier
Imgur Screenshot Uploader
KStatusNotifierItem/AppIndicator Support
No Topleft Hot Corner
NoAnnoyance
Panel OSD
Permanent notifications
Refresh Wifi Connections
Remmina Search Provider
Removable Drive Menu
Remove Dropdown Arrows
Status Area Horizontal Spacing
TopIcons Plus
Transcode App Search
Trash
User Themes
```

**Comment by AccountOneOff** [comment]
@AlexGluck Is the [icons folder](https://github.com/julio641742/extend-panel-menu/tree/master/icons) in your extension folder? It doesn't transfer over when executing the makefile for me so I had to manually copy and paste the folder for it to appear.
