### ISSUE TITLE
Offset icons is broken.

### ISSUE THREAD

**Issue by AlexGluck** [julio641742/extend-panel-menu#40]
Offset between calendar and power indicator very small (here will notification icon).
![2017-07-18 17-10-02](https://user-images.githubusercontent.com/8583390/28321650-74054498-6bdc-11e7-81cb-9223e3d141c7.png)
Offset between Wifi and BT icon is broken, and jump from very big to gigant.

**Comment by AlexGluck** [comment]
For calendar i set hook few spaces "*SPACE**SPACE**SPACE**SPACE*%H:%M*SPACE*%n*SPACE*%e.%m.%Y*SPACE*"
But for WIFI and BT idk.

THX for great works.

**Comment by julio641742** [comment]
Try the latest commit and report back :+1:

**Comment by AlexGluck** [comment]
#44 is duplicate issue, please close. And this issue fixed. Offset is normal. thx. Great work.
