### ISSUE TITLE
Battery percentage next to power icon

### ISSUE THREAD

**Issue by kprinssu** [julio641742/extend-panel-menu#41]
I can enable the battery percentage via `gsettings set org.gnome.desktop.interface show-battery-percentage true`. In the default topbar on GNOME, this works just fine. However, when I enable extend-panel-menu, the above percentage is hidden.

**Comment by AlexGluck** [comment]
May be in this issue can add new feature: hide battery indicator, when AC connected or battery percentage more than 80%.

**Comment by kprinssu** [comment]
Would it be possible to have the icon be displayed with the percentage?

**Comment by julio641742** [comment]
Thanks for your feedback @kprinssu , the battery percentage is now implemented.

I did implement your idea in the latest commit @AlexGluck , however I have not yet tested it extensively so beware of bugs
