### ISSUE TITLE
Notification indicator not changing

### ISSUE THREAD

**Issue by AccountOneOff** [julio641742/extend-panel-menu#42]
Whenever there's a notification pop up the icon doesn't change if the pop up is left alone. I've let a bunch of notifications through without clicking them to test and the indicator doesn't change to signify a missed notification.

Not Spotify, Discord, or KDE Connect.

https://streamable.com/lk2js

**Comment by julio641742** [comment]
Try the latest commit

**Comment by AccountOneOff** [comment]
That's done it. Thank you! :smile:
