### ISSUE TITLE
the calendar is big

### ISSUE THREAD

**Issue by Chanovera** [julio641742/extend-panel-menu#43]
my calendar in really big in your extension 
![captura de pantalla de 2017-07-23 13-22-05](https://user-images.githubusercontent.com/30060622/28501839-249d22fa-6faa-11e7-91cf-32d5dc6b4019.png)

**Comment by julio641742** [comment]
Could you try installing the latest commit

**Comment by Chanovera** [comment]
Works! thank you very much!
