### ISSUE TITLE
Bluetooth and network icons offset to big

### ISSUE THREAD

**Issue by Ixoos** [julio641742/extend-panel-menu#44]
When both bluetooth and network icons are visible, offset beetwen these two icons is too big 
![Image of  the problem](http://i.imgur.com/hRFhlde.png)

**Comment by julio641742** [comment]
Thanks for the feedback, I am working on it :+1:

**Comment by julio641742** [comment]
Try the latest commit and report back please :+1:

**Comment by AlexGluck** [comment]
Offset is normal. thx. Great work.

**Comment by Ixoos** [comment]
Yup, now it's good
