### ISSUE TITLE
Unknown button

### ISSUE THREAD

**Issue by AlexGluck** [julio641742/extend-panel-menu#48]
On mouse over i see button with icon but no label. wtf?
![2017-07-29 02-34-08](https://user-images.githubusercontent.com/8583390/28740014-c9c3635e-7408-11e7-9fc3-5b0a502d6573.png)

**Comment by julio641742** [comment]
fixed

**Comment by AlexGluck** [comment]
Where are you fix? Button on string "Change date format", on click opened url: https://help.gnome.org/users/gthumb/unstable/gthumb-date-formats.html.en
