### ISSUE TITLE
Top Icons extension Goes to right corner.

### ISSUE THREAD

**Issue by syedhabib53** [julio641742/extend-panel-menu#5]
When I restart the gnome-shell,[ TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) will go to right corner.
![screenshot from 2017-05-04 15-24-27](https://cloud.githubusercontent.com/assets/2760976/25698770/d5c1a68e-30dd-11e7-81e1-20f40dc6dc4e.png)

**Comment by julio641742** [comment]
![screenshot from 2017-05-04 17-35-26](https://cloud.githubusercontent.com/assets/14211453/25730284/2d9ba492-30f0-11e7-93de-5f7761c97647.png)
Please change the tray offset to 6 (7 if you use nighlight and Gnome v3.24). That would fix your problem
