### ISSUE TITLE
Player controls not showing up

### ISSUE THREAD

**Issue by AccountOneOff** [julio641742/extend-panel-menu#50]
Sometimes when using Spotify the player controls don't show in the sound indicator and sometimes they do. Could you look into this? I have no idea how to debug this.

Ubuntu 17.04

Gnome Shell 3.24.2

**Comment by julio641742** [comment]
The latest commit should theoretically fix this, please use the code from this repo and report back 👍

**Comment by AccountOneOff** [comment]
Not sure how to test since it was seemingly random when it wouldn't show up. I'll report back if I notice it not showing but so far so good.

**Comment by matteotanca** [comment]
Yes they work in 17.10.

**Comment by AccountOneOff** [comment]
Yeah I haven't noticed this issue pop up at all. I think it's safe to close.
