### ISSUE TITLE
please work on gnome 3.26

### ISSUE THREAD

**Issue by Chanovera** [julio641742/extend-panel-menu#51]

**Comment by julio641742** [comment]
I updated the metadata.json to support gnome 2.26, but I don't have that version of gnome installed in my system. Could you check if the extension works on your system?

**Comment by 4thguy** [comment]
I cloned the repo, deleted the extension, and ran `make` and `make install` still no change

**Comment by toth25b** [comment]
Same problem for me. :/ (Manjaro with Gnome 3.26.0) Please fix it, I really like this extension.

**Comment by pagaiba** [comment]
@julio641742 I can enable it, but it doesn't work. It just vanishes everything it's supposed to let you toggle.

**Comment by Ixoos** [comment]
Same for me :/

**Comment by julio641742** [comment]
I just added support for gnome 2.26, you can try it now and let me know if everything works fine for you

**Comment by glinton** [comment]
Confirmed works on gnome 2.26:

```
$ gnome-shell --version
GNOME Shell 3.26.0

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful
```

**Comment by geeksunny** [comment]
Confirmed working with a fresh make install on 3.26.1. The Shell Extensions version was crashing, though.

**Comment by pagaiba** [comment]
Same, I guess it hasn't been updated yet.

**Comment by FireWolf74** [comment]
It will not work for me.  Please fix. Fedora 27 GNOME 3.26

**Comment by AlexGluck** [comment]
Fedora 27 release today, by default this use GNOME 3.26
It will not work for me. Please fix. Fedora 27 GNOME 3.26

**Comment by julio641742** [comment]
Are you using the extension provided on the gnome extensions website? I have not yet updated the files there. Please try to use the one on this repository and give me some feedback. I want to test it before submitting it to the extensions page. 👍

**Comment by AlexGluck** [comment]
It works even better than it was for me. And text in button fix this 
![-20171116152826-755x798](https://user-images.githubusercontent.com/8583390/32891345-411ff29c-cae3-11e7-9c0c-7552debbe9c0.png)

**Comment by AlexGluck** [comment]
Update ready, please close issue.
