### ISSUE TITLE
Doesn't work with Media Player Indicator (JasonLG1979 extension)

### ISSUE THREAD

**Issue by fcastilloec** [julio641742/extend-panel-menu#52]
When this extension is enabled, only the default Gnome Media Player can be seen, but JasonLG1979 [Media Player extension](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/) doesn't work anymore. I have to disable this extension for Jason's to work properly.
I'm not sure which extension is to blame for not working with each other, but I've posted issue [gnome-shell-extensions-mediaplayer#418](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/418) on their project as well.

**Comment by julio641742** [comment]
Already answered by Jason
