### ISSUE TITLE
Disabled indicators inherit toggle when moved

### ISSUE THREAD

**Issue by AccountOneOff** [julio641742/extend-panel-menu#53]
When an indicator is moved on the list, instead of keeping the the toggle (enable/disable), the indicator above or below it inherits it depending on if it moves up or down.

https://streamable.com/yqspm

**Comment by julio641742** [comment]
Fixed in the latest commit, please try using the code from the repo and report back 👍

**Comment by AccountOneOff** [comment]
It's fixed! Thank you.
