### ISSUE TITLE
Media Player Indicator appears only after you start a media player

### ISSUE THREAD

**Issue by matteotanca** [julio641742/extend-panel-menu#9]
I'd love to start media player from the volume indicator.

**Comment by julio641742** [comment]
I'll look into it

**Comment by matteotanca** [comment]
http://www.omgubuntu.co.uk/2017/05/gnome-extend-panel-menu-extension

**Comment by julio641742** [comment]
Great article, thanks for letting me know

**Comment by julio641742** [comment]
I implemented this on latest commit, however you first have to start a few players in order for the extension to recognize them and save them inside the menu. Please try it and report back 👍

**Comment by matteotanca** [comment]
Hi, I'm using ubuntu 17.10 with Gnome 3.26, cannot find the extension in the site. Should I try from source? Otherwise give me a few days and I'll try it in a 17.04 vm

**Comment by matteotanca** [comment]
![schermata da 2017-11-22 01-57-03](https://user-images.githubusercontent.com/5741224/33104474-a23a2432-cf28-11e7-8944-441722586f79.png)
In Ubuntu 17.10 all is working fine. Using it as default extension atm. Thanks
